apiVersion: v1
kind: Pod
metadata:
  name: postgress-pod
  labels:
    app: postgress-pod
spec:
   containers:
     - name: postgres
       image: postgres:9.4
       ports:
         - containerPort: 5432
       env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
         
        
        