apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: votting-app
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app
    spec:
      containers:
        - name: result-app-pod
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
    
        