# apiVersion: v1
# kind: Pod
# metadata:
#   name: votting-app-pod
#   labels:
#     app: votting-app
# spec:
#    containers:
#      - name: votting-app-pod
#        image: kodekloud/examplevotingapp_vote:v1
#        ports:
#          - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: votting-app-deployment
  labels:
    name: votting-app
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: votting-app
  template:
    metadata:
      name: votting-app-pod
      labels:
        app: votting-app
    spec:
      containers:
        - name: votting-app-pod
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
    



         
        