# apiVersion: v1
# kind: Pod
# metadata:
#   name: worker-app
#   labels:
#     app: worker-app
# spec:
#   containers:
#     - name: worker-app
#       image: kodekloud/examplevotingapp_worker:v1
      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: votting-app
    app: worker-app

spec:
  replicas: 1
  selector:
    matchLabels:
       app: worker-app
  template:
    metadata:
      name: worker-app
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
    